var pageTitlesList = [
  'Medical Terms in Punjabi Translation',
  'How to Report...',
  'Distress and Crisis Lines',
  'Medical Professionals - Punjabi-speaking',
  'Psychologists - Punjabi-speaking',
  'Counselling Services offered in English',
  'Legal Assistance',
  'Court Supports',
  'Emergency Shelters',
  'Domestic Violence Technical Terms translated in Punjabi',
  'Domestic Violence Supports Offered In Punjabi',
  'Domestic Violence Supports Offered in English',
  'Emergency Funding Offered By the Alberta Government',
  'Important Sexual Violence Information translated into Punjabi',
  'Sexual Violence Supports (English)',
  'Physical Health and Mental Health',
  'Addiction Supports (English)',
  'Addiction Supports (Punjabi)',
];